name: 'Setup Conda'
description: 'Create conda environment for GitHub Action Job'

runs:
  using: "composite"
  steps:
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if '.ci_helpers/py{0}.yaml' has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('binder/environment.yml') }}
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: echopype
        # environment-file: binder/environment.yml
        environment-file: .ci.environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: 4.10.0-0
        use-mamba: true
        auto-activate-base: false
        use-only-tar-bz2: true
