name: echopype
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - ipykernel
  # Remove echopype version pinning for now
  - echopype
  - s3fs
  - geopandas
  - cartopy
  # -- holoviz --
  - datashader
  - holoviews
  - hvplot
