name: echopype
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - ipykernel
  - echopype==0.7.0
  - s3fs
  - geopandas
  - cartopy
  # -- holoviz --
  - datashader
  - holoviews
  - hvplot
