name: echopype
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - echopype
  # - echopype=0.6.0
  - s3fs
  - geopandas
  - cartopy
  # -- holoviz --
  - datashader
  - holoviews
  - hvplot
